# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 686fb2e269a07bf118a0b64becf6d2077633c1213722a1a622a1cd1b567758032eedb5137b4117cb7b8153577fcf0590c5b04af9593bcd001a0c069f3c045195

test:
  secret_key_base: cbbfde37800a256f680bee08932c4b0c9881a947fc93ca644427bd2d43ca812b20610a4dfc77616518b303b42046d573ba2c37a660e71c8ce4e3545817607e30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
